"""empty message

Revision ID: 6bb9d547cead
Revises: cd2fd1cbc016
Create Date: 2024-12-04 07:14:56.606838

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2          # POSTGIS


# revision identifiers, used by Alembic.
revision = '6bb9d547cead'
down_revision = 'cd2fd1cbc016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('spotify_preview_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('spotify_duration_ms', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audio_analyses_spotify_id'), ['spotify_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_analyses_spotify_id'))
        batch_op.drop_column('spotify_duration_ms')
        batch_op.drop_column('spotify_preview_url')
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###
