"""empty message

Revision ID: 9bdcb162a3bc
Revises: 
Create Date: 2024-12-03 13:35:00.671053

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2          # POSTGIS
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bdcb162a3bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('audio_analyses',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('key', sa.String(length=10), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.Column('time_signature', sa.String(length=10), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('loudness', sa.Float(), nullable=True),
    sa.Column('speechiness', sa.Float(), nullable=True),
    sa.Column('acousticness', sa.Float(), nullable=True),
    sa.Column('instrumentalness', sa.Float(), nullable=True),
    sa.Column('liveness', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('mood_confidence', sa.Float(), nullable=True),
    sa.Column('voice_characteristics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_audio_analyses_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_audio_analyses_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_analyses'))
    )
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_analyses_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_analyses_title'), ['title'], unique=False)

    op.create_table('files',
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('remote_name', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='FileStatus_enum', native_enum=False), nullable=True),
    sa.Column('file_type', sa.Enum('export', 'import', 'image', 'audio', 'video', 'pdf', name='FileType_enum', native_enum=False), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_mime_type'), ['mime_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_mime_type'))

    op.drop_table('files')
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_analyses_title'))
        batch_op.drop_index(batch_op.f('ix_audio_analyses_artist'))

    op.drop_table('audio_analyses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
