"""empty message

Revision ID: bfcff6967d7e
Revises: 9bdcb162a3bc
Create Date: 2024-12-03 13:38:58.921012

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2          # POSTGIS
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfcff6967d7e'
down_revision = '9bdcb162a3bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('spotify_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('tempo')
        batch_op.drop_column('segments')
        batch_op.drop_column('acousticness')
        batch_op.drop_column('key')
        batch_op.drop_column('mood_confidence')
        batch_op.drop_column('voice_characteristics')
        batch_op.drop_column('mode')
        batch_op.drop_column('mood')
        batch_op.drop_column('liveness')
        batch_op.drop_column('instrumentalness')
        batch_op.drop_column('time_signature')
        batch_op.drop_column('danceability')
        batch_op.drop_column('valence')
        batch_op.drop_column('loudness')
        batch_op.drop_column('speechiness')
        batch_op.drop_column('energy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('energy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('speechiness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('loudness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('valence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('danceability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time_signature', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('instrumentalness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('liveness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mood', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mode', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('voice_characteristics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mood_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('acousticness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('spotify_info')
        batch_op.drop_column('track_name')

    # ### end Alembic commands ###
