"""empty message

Revision ID: cd2fd1cbc016
Revises: bfcff6967d7e
Create Date: 2024-12-03 17:57:05.386305

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2          # POSTGIS


# revision identifiers, used by Alembic.
revision = 'cd2fd1cbc016'
down_revision = 'bfcff6967d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
