"""empty message

Revision ID: e5b2308b54ba
Revises: 6bb9d547cead
Create Date: 2024-12-10 08:18:45.991383

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2          # POSTGIS
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5b2308b54ba'
down_revision = '6bb9d547cead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
